[package]
name = "ch6-uniqr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.50"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
rand = "0.10.0-rc.0"
tempfile = "3.23.0"
